### ISSUE TITLE
[FEAT]: render erasing effect offscreen

### ISSUE THREAD

**Issue by ShaMan123** [ShaMan123/erase2d#16]
I wonder if that can be done if fabric currently

**Comment by mtrabelsi** [comment]
Are you supporting offscreencanvas?
not quit clear what is this issue about thx

**Comment by ShaMan123** [comment]
Fabric does not support offscreen. I had a pr for that but it was closed.
Therefore, erasing can be done offscreen but not with fabric.
Also the erasing effect might be too delayed if you do it offscreen. Up to you.
You can try to move the eraser brush canvases offscreen...

**Comment by ShaMan123** [comment]
This ticket is here to make the drawing of the erasing effect canvas offscreen, nothing else.
But that depends on fabric object rendering. It sounds possible but messy.
All in all it is a perf opt to reduce the freeze time on mousedown.

**Comment by ShaMan123** [comment]
I think it is a waste of time, that is why I didn't do it.
