### ISSUE TITLE
what is the overall approach to realize eraser function ?

### ISSUE THREAD

**Issue by tianmuji** [ShaMan123/erase2d#18]
Reading your source code, it seems to be
first you override all onMouse function,
when onMouseDown triggered, you call drawEffect and parent class onMouseDown method
when onMouseMove, just call parent class onMouseMove and dispatch move event
when onMouseUp, additionally call disposer initialized in onMouseDown event, which will call erase and drawEffect method

I do not quite understand clipping the destination context and compositing it with the source context
And why you use effectContext
Could you please explain a lit bit more in detail?
Thank you so much

**Comment by ShaMan123** [comment]
The erasing effect is what gives a visual feedback of erasing only erasable entities.
It does that by redrawing what is not erasable on top of the erased path.
For the undoing effect it redraws all objects without their erased part, as per the fabric binding.
To construct a binding you need something like a brush.
Then you hook into its lifecycle as you described.
There is a listener that is disposed on mouse up that listens to the canvas rendering in case something changes while erasing so that the erasing effect is updated accordingly. Without it if something changes on the canvas (e.g. animation) the erasing effect will show the stale visual state it captured on mouse down.
Hope that helps

**Comment by tianmuji** [comment]
> The erasing effect is what gives a visual feedback of erasing only erasable entities. It does that by redrawing what is not erasable on top of the erased path. For the undoing effect it redraws all objects without their erased part, as per the fabric binding. To construct a binding you need something like a brush. Then you hook into its lifecycle as you described. There is a listener that is disposed on mouse up that listens to the canvas rendering in case something changes while erasing so that the erasing effect is updated accordingly. Without it if something changes on the canvas (e.g. animation) the erasing effect will show the stale visual state it captured on mouse down. Hope that helps

Thank you for your reply!
For some reason, canvas.drawImage api dose not accept canvas as first parameter in mobile app. 
it only accepts ImageSource, which means I can only draw image to canvas, I can not draw canvas to canvas
the erase function rely on this feature。

so I need to come up a new way to achieve eraser function

my approach is to set lower context globalCompositeOperation to 'destination-out' and then draw brush path on lower canvas.(it will erase all objects which is bad)
1: onMusedown, set lower context globalCompositeOperation to 'destination-out'
2: onMousemove, draw path on the lower context, which can simulate erasing effect
3: onMouseup, reset globalCompositeOperation to source-over

But I found that when mousemove, the lower context seems to be cleaned.
I guess that is because the context transfrom is not reset
I reset it but does not work

Could you please give me some suggestions on fixing this or a new approach to do eraser without using canvas.drawImage

**Comment by ShaMan123** [comment]
> For some reason, canvas.drawImage api dose not accept canvas as first parameter in mobile app. it only accepts ImageSource, which means I can only draw image to canvas, I can not draw canvas to canvas the erase function rely on this feature。

I do not know anything about the engine you are using but you could probably export the canvas to an image...


If you do not need an erasing effect, meaning you ONLY need to erase the entire canvas without considering non erasable objects then drawing the path with destination out should do the job

**Comment by ShaMan123** [comment]
closing as stale

**Comment by ShaMan123** [comment]
feel free to reopen
