### ISSUE TITLE
[Bug]: There is a bug where drawing with the brush and erasing with the eraser leaves an afterimage.

### ISSUE THREAD

**Issue by skulter** [ShaMan123/erase2d#19]
### Version
5.3.0

### In What environments are you experiencing the problem?
Chrome

### Node Version (if applicable)
None

### Link To Reproduction
https://codepen.io/hoqcaeiq-the-animator/pen/MWROpwx

### Steps To Reproduce
1. draw a picture with the brush.
2. Use the eraser to erase the drawing with very slow movements.
### Expected Behavior
Normal behavior is that even if the eraser moves very slowly, the area it passes over should be cleanly erased.

### Actual Behavior
As you can see in the video, there is an afterimage and you can see the afterimage even if you change the color.

This bug is in 5.3, but the same bug occurs in 4.4.
I would like to know how to fix it.

In the official example, you can see that the same bug occurs if you set the width of the eraser brush to high and then move it very slowly to erase.

Thanks for listening
![eraser_bug](https://github.com/ShaMan123/erase2d/assets/18344213/f8752e29-486a-4832-a816-7fa502873746)
![MicrosoftTeams-image (1)](https://github.com/ShaMan123/erase2d/assets/18344213/9be179da-6049-4f96-a3b8-39b6568e38b2)
![MicrosoftTeams-image](https://github.com/ShaMan123/erase2d/assets/18344213/496b012e-e8cc-409d-bdc4-c88c0466d22f)

**Comment by ShaMan123** [comment]
I saw you opened an issue regarding fabric's pencil brush in general, so it seems the problem doesn't originate from the eraser.
I didn't know that.
You can try to workaround by creating a different brush impl using different bezier logic and see if that changes anything.
The eraser is a visual effect over the existing pencil brush so hopefully that will do the job.
I guess this falls under aliasing. I thought imagr smoothing will therefore make a difference but it seems it didn't. Keep that in mind.

**Comment by skulter** [comment]
That's right. I've opened a new issue for the pencil brush.
hope you'll take a look and thank you for your response.
I'll be sure to let you know if it gets resolved.
