### ISSUE TITLE
How to simulate Eraser on another Canvas programmatically

### ISSUE THREAD

**Issue by mtrabelsi** [ShaMan123/erase2d#22]
in V5 I used to use eraser brush on another canvas without mouse being involved, but its unclear with the V6 how can this be done.

```
 
  const simulateEraser = (x, y) => {
                        const fakeEvent = {..}

                        const pointer = new fabric.Point(x, y);
                      
                        // Simulate mouse down, move, and up to "draw" with the eraser
                    
  
        }
        
        
                         simulateEraser(100, 150);

```

**Comment by ShaMan123** [comment]
Looks alright in a quick glance.

**Comment by mtrabelsi** [comment]
once i'm finished with the migration i will report my test if it works or not, I can not test it right now

**Comment by ShaMan123** [comment]
I don't know what you want to achieve so I am dropping a lead
https://webrtc.github.io/samples/src/content/capture/canvas-pc/

**Comment by mtrabelsi** [comment]
Hi @ShaMan123  thanks for getting back, while the simulation previously shown works fine with Fabric 5.x because I could capture x,y of the mouse and then simulate it to another canvas, however with fabric 6 I'm struggling a bit with paths,since i have no direct X,Y after eraser is finished, i could get the path of the eraser:


         ```
                 eraser.on('end', (e) => {
                 //   e.preventDefault();  // Prevent automatic committing

                    const {path, ...rest} = e.detail.path
                    const scaleFactor = hiddenCanvasRef.current.width / canvasRef.current.width;

                    const newPath = new Path(path, {
                      ...rest,
                      scaleX: scaleFactor,
                      scaleY: scaleFactor
                  });

                    // Center the path on the canvas
                    const relativeLeft = rest.left * scaleFactor;
                    const relativeTop = rest.top * scaleFactor;
                
                    newPath.set({
                        left: relativeLeft,
                        top: relativeTop
                    });
                
                    hiddenCanvasRef.current.add(newPath);
                    hiddenCanvasRef.current.renderAll();

                    // foregroundImg is the image to be erased
                    const foregroundImg = hiddenCanvasRef.current.getObjects().find(obj => obj.name === "foreground");
                
                    hiddenCanvasRef.current.renderAll();

                  }); 
```


While this works perfectly, as soon as you drag the image the eraser path will not move with the image, it seems that its not "merged" with the image object (foregroundImg) any idea how could be achieved?

**Comment by ShaMan123** [comment]
Look at the utils, there are method that help you add an eraser to a fabric object

**Comment by mtrabelsi** [comment]
Many thanks!


Unfortunately I see no real difference by using these or directly adding the path, the path remained "detached" from the image that is loaded despite merging :



```

      
                    const newPath = new Path(path, {
                      ...rest,
                      scaleX: scaleFactor,
                      scaleY: scaleFactor,
                     preserveObjectStacking: true,
                  });

                    // Center the path on the canvas
                    const relativeLeft = rest.left * scaleFactor;
                    const relativeTop = rest.top * scaleFactor;
                
                    newPath.set({
                        name: 'eraserPath',
                        left: relativeLeft,
                        top: relativeTop,
                    });
                
               
    
                
                    const foregroundImg = hiddenCanvasRef.current.getObjects().find(obj => obj.name === 'foreground');
                    
                    if (foregroundImg) {
                      //newPath.inverted = true; // Ensure it subtracts
              
                      if (foregroundImg.clipPath) {
                          // If there's an existing clip path, merge them
                          foregroundImg.clipPath = await cloneAndClip(newPath, foregroundImg);
                      } else {
                          // Apply as new clip path
                         // foregroundImg.clipPath = newPath;
                         // fabricjs remove object from canvas
                         hiddenCanvasRef.current.add(newPath);

                      }
                      
                      foregroundImg.dirty = true;  // Mark the object as needing a re-render
                      hiddenCanvasRef.current.renderAll();
                      
                  }
                
```

**Comment by ShaMan123** [comment]
Add a live repro using codesandbox

**Comment by mtrabelsi** [comment]
Hi @ShaMan123 

thanks!

there you go, I was able to reproduce it here: https://codesandbox.io/p/sandbox/little-paper-3oqi6s

- start by erasing on the red Canvas - do not drag the image for now -
- you will see that erasing works on the black Canvas.
- now switch to drag mode and drag the black Canvas, you will see the eraser is just floating not really "merged" with the image.

in this case the eraser path goes below the image, by in my real code it stays in front - not important, the most important thing is to be able to erase with the path programatically without user interaction

Thanks!

**Comment by mtrabelsi** [comment]
NOTE: for some reasons this block is always executed, that is not the case on my localhost, however the result is the same

![image](https://github.com/ShaMan123/erase2d/assets/7538862/83ed32be-8dc2-47d0-acdc-95e90fe28176)

**Comment by mtrabelsi** [comment]
seems that adding the path to the canvas directly is not a smart way, its like adding object seperatly and will not work, I have tried this seems to do something thay you previously suggested but in a wrong way, the image on the right becomes completely white, my guess because the eraser path has no intersection with the object thus the clippath is empty:

```

      if (foregroundImg.clipPath) {
          // If there's an existing clip path, merge them
          console.log("erase for the second time and beyond", foregroundImg.width, foregroundImg.height);
          foregroundImg.clipPath = await cloneAndClip(path, foregroundImg);
        } else {
          console.log("erase for the first time");
          const t = foregroundImg.calcTransformMatrix();
          foregroundImg.clipPath = await clipObject(foregroundImg, path, t); 
        }
```

**Comment by mtrabelsi** [comment]
ok here is the another codebox: https://codesandbox.io/p/sandbox/little-paper-3oqi6s

this is where I started weeks before, the image size matters to see the effect, the eraser does not look correct on the black canvas even though I have used the utils function for erasing

**Comment by mtrabelsi** [comment]
looks like I have found an alternative workaround, from path i was able to generate the list of points i could then simulate clicking there... its too slow on mobile but i will find how to improve it.
maybe by cropping the bounding box of the eraser path, do the manipulation offscreen, then merge it back, it might be much faster than directly manipulating a 4k image on mobile.

**Comment by ShaMan123** [comment]
Take a look at what I did to the `end` event handler in your app:

```js

    eraser.on("end", (e) => {
      const foregroundImg = hiddenCanvasRef.current
        .getObjects()
        .find((obj) => obj.name === "foreground");

      e.detail.targets.push(foregroundImg);
      // Or call commit directly if you wish to execute something once it completes (covert the callback to async)
      // await eraser.commit({ path, targets: [foregroundImg] });
      hiddenCanvasRef.current.requestRenderAll();
    });
```
https://codesandbox.io/p/sandbox/fabricjs-eraser-forked-xxmx44?file=%2Fsrc%2Fapp.js%3A107%2C4-116%2C8

**Comment by ShaMan123** [comment]
If you wish to erase the other image so it is erased exactly as the source image regardless of transform changes:

```js
    eraser.on("end", async (e) => {
      const foregroundImg = hiddenCanvasRef.current
        .getObjects()
        .find((obj) => obj.name === "foreground");
      const path2 = await e.detail.path.clone(["inverted"]);
      util.sendObjectToPlane(
        path2,
        util.invertTransform(e.detail.targets[0].calcTransformMatrix()),
        util.invertTransform(foregroundImg.calcTransformMatrix())
      );
      await eraser.commit({ path: path2, targets: [foregroundImg] });
      hiddenCanvasRef.current.requestRenderAll();
    });

```
https://codesandbox.io/p/sandbox/fabricjs-eraser-forked-xt57s3

**Comment by ShaMan123** [comment]
That is really cool! Maybe I should add it to the official demo.

**Comment by ShaMan123** [comment]
https://github.com/ShaMan123/erase2d/assets/34343793/c052cc27-c32f-4e64-ad9a-327fdd7fc677


https://github.com/ShaMan123/erase2d/assets/34343793/2a25ecc7-8d8e-4b68-bf64-d2ca21ab1c46
