### ISSUE TITLE
The eraser cannot function properly in scenes with PencilBrush and background images

### ISSUE THREAD

**Issue by wangqingbang-austin** [ShaMan123/erase2d#27]
When I use the **PencilBrush** component to draw marker content, the eraser does not work properly.

and the background image, even if **erasable: false** is set, will still be erased by the eraser.

Here is my code：

![image](https://github.com/ShaMan123/erase2d/assets/63333691/26a4f148-e9b0-44d3-8374-816e975fea22)
![image](https://github.com/ShaMan123/erase2d/assets/63333691/996b128e-8a5d-4848-8632-53fbdcc8c9e7)
![image](https://github.com/ShaMan123/erase2d/assets/63333691/3e7c6904-dd8b-4154-83b2-69f4e7b5f80b)

**Comment by ShaMan123** [comment]
This repo is all about erasing.
I don't see any eraser components in your code.

**Comment by wangqingbang-austin** [comment]
![image](https://github.com/ShaMan123/erase2d/assets/63333691/9b2ea13a-a448-4d76-9f7a-8892c23db952)

This is my code. 

When using an eraser, the pencil brush did not erase it, but the background image was erased.

**Comment by ShaMan123** [comment]
Hard to understand what is expected and what is actual.
Please describe, add visuals ad a live repro on codesandbox

**Comment by ShaMan123** [comment]
anyways make sure you set the pencil brush result to be erasable

**Comment by ShaMan123** [comment]
closing due to no response

**Comment by whace** [comment]
how to set pencil brush can bei erasable.
