### ISSUE TITLE
Install via yarn not working

### ISSUE THREAD

**Issue by raulfelix** [ShaMan123/erase2d#31]
Hello, we use yarn instead of npm and seem unable to add this package to our project.

`yarn add @erase2d/fabric`

**Error**
```
error Package "" refers to a non-existing file
```

**Env**
MacOS 14.5
Yarn version: 1.22.19

Any ideas?

**Comment by ShaMan123** [comment]
maybe yarn has issues with orgs ("@erase2d")

**Comment by raulfelix** [comment]
I don't think yarn likes this reference in the `package.json` as the file is not found on my local system. Perhaps npm ignores it? Does this library depend on core? 
```
"dependencies": {
    "@erase2d/core": "file:../core"
  },
```
