### ISSUE TITLE
opcacity will be reset after erasing

### ISSUE THREAD

**Issue by KKzLEO** [ShaMan123/erase2d#37]
hi,
thanks for creating this awesome library, it's really helpful, but I encouter a bug that the opacity of objects will be reset to 1 after erasing, do we have some workaround to fix it? thanks!

**Comment by ShaMan123** [comment]
Please add a codesandbox repro.
I think I noticed something as well and wasn't sure if it was a bug here or in fabric.
Did you use groups?
