### ISSUE TITLE
canvas.loadFromJSON error

### ISSUE THREAD

**Issue by franckdsf** [ShaMan123/erase2d#42]
Hey, 
I've been trying to implement the undo method but couldn't manage to do it the way you described in [issue#39](https://github.com/ShaMan123/erase2d/issues/39#issuecomment-2198053390).

So I decided to save the canvas as JSON instead and reload the canvas on undo requests. But it looks like it breaks the Eraser; it's not possible to erase after that.

```ts
import type { Canvas } from "fabric/es";
import { useCallback, useEffect, useState } from "react";

export const useUndo = (canvas: Canvas | null) => {
  const [undoStack, setUndoStack] = useState<Array<JSON>>([]);

  const undo = useCallback(() => {
    if (undoStack.length === 0 || !canvas) return false;

    // get latest state
    const previousState = undoStack[undoStack.length - 1];
    if (!previousState) return false;

    // remove it from the undo stack
    setUndoStack((prev) => prev.slice(0, prev.length - 1));

    // reload the canvas with the state
    canvas.cancelRequestedRender();
    canvas.loadFromJSON(previousState)
      .then(() => { canvas.renderAll(); })
      .catch(() => null)

    return true;
  }, [undoStack, canvas]);

  const saveCanvas = useCallback(() => {
    if (!canvas) return;
    const json = canvas.toJSON() as JSON;
    setUndoStack((prev) => [...prev, json])
  }, [canvas])

  useEffect(() => {
    if (!canvas) return;
    // whenever an action is made, save the current state
    canvas.on('mouse:down:before', saveCanvas)
    return () => { canvas.off('mouse:down:before', saveCanvas); }
  }, [canvas, saveCanvas])

  return { undo };
}
```

Here is the CodeSandbox [link](https://codesandbox.io/p/devbox/erase2d-fabric-loading-from-json-issue-hvh254?file=%2Fsrc%2Fhooks%2FuseUndo.ts%3A10%2C24&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly0s34q70007356jzp6v32qo%2522%252C%2522sizes%2522%253A%255B79.78243238626243%252C20.21756761373757%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly0s34q70002356j0nsf3ccm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly0s34q70004356jey6l6n3q%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly0s34q70006356j25ielpj6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly0s34q70002356j0nsf3ccm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly0s34q70001356jtrujxnoe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly0s4x3z0002356jc583o6ek%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly0s85pb0002356jmjgxp520%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fhooks%252FuseUndo.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cly0sblw20002356jhpjqox8m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A19%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fhooks%252FuseKeyPressed.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cly0s34q70002356j0nsf3ccm%2522%252C%2522activeTabId%2522%253A%2522cly0s85pb0002356jmjgxp520%2522%257D%252C%2522cly0s34q70006356j25ielpj6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly0s34q70005356j7nudjsia%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cly0s34q70006356j25ielpj6%2522%252C%2522activeTabId%2522%253A%2522cly0s34q70005356j7nudjsia%2522%257D%252C%2522cly0s34q70004356jey6l6n3q%2522%253A%257B%2522id%2522%253A%2522cly0s34q70004356jey6l6n3q%2522%252C%2522activeTabId%2522%253A%2522cly0skfur00a7356je3dquzfp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly0s34q70003356jue79sbv6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522install%2522%252C%2522id%2522%253A%2522cly0skfur00a7356je3dquzfp%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

To replicate the behavior, erase the image, click the undo button, and try to erase again.

Does it have something to do with the *dirty* state you mentioned ?

Thanks!

**Comment by franckdsf** [comment]
**Update**: 

On an other project using the same hook and same ``@erase2d/fabric`` and ``fabric`` version, I even get an error while loading the JSON

```
Error: fabric: No class registered for clipping
    at o.getClass (ClassRegistry.min.mjs:9:125)
    at eval (objectEnlive.min.mjs:11:1055)
    at Array.map (<anonymous>)
    at eval (objectEnlive.min.mjs:11:981)
    at new Promise (<anonymous>)
    at i (objectEnlive.min.mjs:11:892)
    at eval (objectEnlive.min.mjs:11:1467)
    at Array.map (<anonymous>)
    at eval (objectEnlive.min.mjs:11:1450)
    at new Promise (<anonymous>)
    at a (objectEnlive.min.mjs:11:1350)
    at g._fromObject (Object.min.mjs:28:17691)
    at g.fromObject (Path.min.mjs:17:4276)
    at eval (objectEnlive.min.mjs:11:1072)
    at Array.map (<anonymous>)
    at eval (objectEnlive.min.mjs:11:981)
    at new Promise (<anonymous>)
    at i (objectEnlive.min.mjs:11:892)
    at E.loadFromJSON (StaticCanvas.min.mjs:25:15244)
    at eval (useUndo.ts:17:12)
```
```ts
    canvas.loadFromJSON(previousState)
      .then(() => { canvas.renderAll(); })
      .catch((e) => console.log(e)) // ERROR
```

> This happened in the CodeSandbox too but I don't know how I managed to fix it...

**Comment by ShaMan123** [comment]
Don't do that because it will kill perf at some point.
To fix the json issue try:


fabric.classRegistry.setClass(ClippingGroup)

**Comment by ShaMan123** [comment]
> Don't do that because it will kill perf at some point.

Depends on your app and production usage.
I have a prod app that does history like that becuase the data is very light and others apps which can't.

**Comment by franckdsf** [comment]
> fabric.classRegistry.setClass(ClippingGroup)

This indeed solved the error: ``Error: fabric: No class registered for clipping.``

> Depends on your app and production usage

My canvas only consists of a few layers, so this should be manageable.

However, for the other issue, it still doesn't work. 
Actually, I've been testing new things to better understand the problem, and it looks like once we use ``loadFromJSON``, we cannot erase things prior to loading. But if we add a new object to the canvas and try to delete it, it works. Only the objects added before loading don't work.

**Comment by franckdsf** [comment]
**Update**

Okay, so the error comes from the fact that when exporting to JSON, ``fabric`` doesn't take into account custom properties such as the ``erasable`` one. For now we have to add them back manually 🤔

**Comment by franckdsf** [comment]
```ts
const customProperties = ['erasable', 'selectable'];
const canvasCopy = canvas.toDatalessJSON(customProperties) as JSON;
 ```
  
Using ``toDatalessJSON`` seems to be the way to go, properties such as ``selectable`` or ``erasable`` are not exported in the JSON since they are custom properties.

The whole undo hook looks sort of like this :

```ts
import type { Canvas } from "fabric/es";
import { useCallback, useEffect, useState } from "react";

export const useUndo = (canvas: Canvas | null) => {
  const [undoStack, setUndoStack] = useState<Array<JSON>>([]);

  const undo = useCallback(() => {
    if (undoStack.length === 0 || !canvas) return;

    const previousState = undoStack[undoStack.length - 1];
    if (!previousState) return;

    setUndoStack((prev) => prev.slice(0, prev.length - 1));

    canvas.cancelRequestedRender();
    canvas.loadFromJSON(previousState)
      .then(() => canvas.renderAll())
      .catch(() => null)
  }, [undoStack, canvas]);

  const saveCanvas = useCallback(() => {
    if (!canvas) return;

    const customProperties = ['erasable', 'customType', 'selectable', 'exportable'];
    const canvasCopy = canvas.toDatalessJSON(customProperties) as JSON;

    setUndoStack((prev) => [...prev, canvasCopy])
  }, [canvas])

  useEffect(() => {
    if (!canvas) return;
    canvas.on('mouse:down', saveCanvas)
    return () => { canvas.off('mouse:down', saveCanvas); }
  }, [canvas, saveCanvas])

  return { undo };
}
```

This issue can be closed 😊
