### ISSUE TITLE
How can i erased PencilBrush, i can eraser Text, but it is not work to pencil brush. and the EraserBrush has black stroke.

### ISSUE THREAD

**Issue by whace** [ShaMan123/erase2d#43]
![image](https://github.com/ShaMan123/erase2d/assets/20571798/05ae065c-30cb-4211-a895-72ebd3f58d0d)
![image](https://github.com/ShaMan123/erase2d/assets/20571798/63c0bfb2-444c-4a82-8cd8-782468368eee)

**Comment by ShaMan123** [comment]
You need to set it to be erasable
You can listen to the brush path:created event and do
path.erasable = true

**Comment by whace** [comment]
> You need to set it to be erasable You can listen to the brush path:created event and do path.erasable = true

Thank you.
