### ISSUE TITLE
Can't clone an erased fabric object 

### ISSUE THREAD

**Issue by hamzawain7** [ShaMan123/erase2d#44]
I am getting the following error when trying to clone an erased fabric object because your clipping group class doesn't exist in fabric:

Error: fabric: No class registered for clipping
    at ClassRegistry.getClass (ClassRegistry.ts:30:13)
    at objectEnlive.ts:109:12
    at Array.map (<anonymous>)
    at objectEnlive.ts:107:15
    at new Promise (<anonymous>)
    at enlivenObjects (objectEnlive.ts:103:3)
    at objectEnlive.ts:159:16
    at Array.map (<anonymous>)
    at objectEnlive.ts:153:54
    
    
  By the way, do I need to do something with the src/mixins/eraser_brush.mixin.ts file in fabricjs? I am also getting ts errors if I need to access the erasable property of fabric objects.

**Comment by ShaMan123** [comment]
fabric.classRegistry.setClass(ClippingGroup)

_Originally posted by @ShaMan123 in https://github.com/ShaMan123/erase2d/issues/42#issuecomment-2198466400_

It should be handled under the hood...
Maybe a matter of import order.

**Comment by hamzawain7** [comment]
Okay, nevermind. This was due to me using a fork of fabric. Your code was using the classRegistry of the original fabric. Thanks.
