### ISSUE TITLE
How should I use Fabricjs 5.3 version

### ISSUE THREAD

**Issue by xiaoli1999** [ShaMan123/erase2d#46]
I want to use brushes in version 5.3. I have read the document you wrote and it should be used in conjunction with version 6.0.
How to use version 5.3? I didn't understand what you wrote. Do you have any examples?

**Comment by ShaMan123** [comment]
In 5.3 it is part of fabric.
http://fabricjs.com/erasing

You will need a [custom build](https://github.com/fabricjs/fabric.js/tree/5.x?tab=readme-ov-file#building):

https://github.com/fabricjs/fabric.js/blob/58bc07d9d8f04b4c7dc8dcd0f617fc00ffde02bf/package.json#L48

```bash
cd node_modules/fabric && npm i && node build.js modules=ALL requirejs exclude=gestures,accessors
```

**Comment by xiaoli1999** [comment]
> In 5.3 it is part of fabric. http://fabricjs.com/erasing
> 
> You will need a [custom build](https://github.com/fabricjs/fabric.js/tree/5.x?tab=readme-ov-file#building):
> 
> https://github.com/fabricjs/fabric.js/blob/58bc07d9d8f04b4c7dc8dcd0f617fc00ffde02bf/package.json#L48
> 
> ```shell
> cd node_modules/fabric && npm i && node build.js modules=ALL requirejs exclude=gestures,accessors
> ```

Thank you very much for your answer!
But this is not the best practice for me. Do you have an npm package for Fabric JS 5.3?

**Comment by ShaMan123** [comment]
No
You can copy the file manually and audit it to use es6
