### ISSUE TITLE
How to do an undo on this eraser ?

### ISSUE THREAD

**Issue by davidanquetin** [ShaMan123/erase2d#47]
Hello
I am searching how to do an Undo on an Eraser action ?

I tried 
```
const eraser = new EraserBrush(myCanvas);
eraser.on('end', (e) => {
     setTimeout(()=>{
	 myCanvas.remove(e.detail.path)
          //or tried eraser.inverted = true
     }, 2000)
```

but it seems not to be the good method.
Is the path of Eraser similar to another canvas object ? It seems not to be in `canvas.getObjects()` ?..

thanks in advance

**Comment by ShaMan123** [comment]
Checkout the [readme](https://github.com/ShaMan123/erase2d/tree/master/packages/fabric#quick-start).
You should preventDefault and call `commit` yourself. That will return a record with the data you need. Then remove the paths from the object's clip path.

**Comment by davidanquetin** [comment]
Thanks ! I will check this documentation, which is unfortunately not clearly mentioned anywhere ..

**Comment by davidanquetin** [comment]
ok, my error was to not call canvas.renderAll() after deleting the target clipPath !
Thanks
